### PR TITLE
county color fill/line change

### PR DESCRIPTION
**Pull request by azadag**
color change!
image

### CODE REVIEW

**Comment by clhenrick** [comment]
@azadag thanks for the suggestion, would you mind pointing to an issue this PR addresses in either a Github issue or Trello card? Thanks!

**Comment by azadag** [comment]
I think it needs to be comprehensively discussed regarding levels of protections. 

we may want to keep colors the same for protection levels but differentiate geographies with border colors. 

https://trello.com/c/2TDAn2Rx/7-improve-color-scheme-create-a-better-visual-way-to-distinguish-between-strong-and-weak-protections-research-team-could-categoriz

**Comment by clhenrick** [comment]
@azadag I'm closing this PR as I can't seem to reopen a new PR with the `cartocounties` branch that @timhitchins merged then reverted today. I want to reopen the original so that we can review and eventually re-merge it after we figure out a work around for the CARTO sync issue.

**Comment by clhenrick** [comment]
also @azadag feel free to submit another PR with your changes in a different branch name then `cartocounties`

**Pull request closed without merging**
