### PR TITLE
Show all paragraphs

### PR DESCRIPTION
**Pull request by djbusstop**
Uncomments paragraph 3, and replaces the placeholder text in English with a blank string.

### CODE REVIEW

**Review by timhitchins — APPROVED** [review]
Simple enough.  Thanks!

**Comment by unixjazz** [comment]
River: could you rebase with main / master? Tim introduced changes recently to 'en.json' and we updated all the language files (based on the updated 'en.json' ).

**Comment by djbusstop** [comment]
@djbusstop fix ur conflicts yoo

**Comment by unixjazz** [comment]
@djbusstop this is PR is stale... and it depends on another open issue that is still open AFAIK:

https://github.com/antievictionmappingproject/covid-19-map/pull/157/files

We cannot merge this change... until the links w/ the documentation about the methodology and the tabular view of the data is ready: @azadag may know the status of these two.

**Pull request closed without merging**
