### PR TITLE
fix to address issue #114 and #115 - don't merge yet, fixing other issues

### PR DESCRIPTION
**Pull request by jimboweb**
Just removed the 50% height on mobile which no longer goes with the current design.

### CODE REVIEW

**Comment by clhenrick** [comment]
@jimboweb I remember there being some JavaScript related to this as well, I think relating to the map popup open event listener. Might be good to remove it as well.

**Comment by clhenrick** [comment]
Also @jimboweb are you looking at the mobile preview on a browser either by using dev tools or shrinking your browser size to be more narrow? You will need to do this to debug the mobile issues, right now your code changes don't resolve the issue:

Screen Shot 2020-07-20 at 10 57 59

**Comment by jimboweb** [comment]
Sorry I guess I didn't understand the problem. So we do want the window to go to 50% and be under the infowindow, right?

**Comment by clhenrick** [comment]
@jimboweb i can't speak to how the current & planned design changes affect this bug fix, but I would imagine fixing this before those changes are made would be beneficial. 

To get an idea of how this was working previously I would recommend that you go back in git history to the commit just prior to the one that added the search bar, and then run the app locally.

**Pull request closed without merging**
