### PR TITLE
Validate localisations with test

### PR DESCRIPTION
**Pull request by djbusstop**
I wrote a jest test which validates that the locale files have the same keys. It may be able to be improved. Let me know what you think.

### CODE REVIEW

**Comment by timhitchins** [comment]
Awesome!  Should we maybe add testing instructions to the README as well?

**Comment by djbusstop** [comment]
Great idea, thank you! I did that just now @timhitchins 

I changed it so that it only checks against english. This makes the most sense to me than comparing against everything else, as this would be confusing to go and hunt down issues if that other file is wrong. English is most likely to be up to date.

**Comment by unixjazz** [comment]
Hi River!  
Here is my belated review: I tested this feature and it does work, flagging keys that are missing in a new translation file.

I have one minor suggestion before this is merged:
* it would be better IMHO if you combine the declaration of translation objects and their path from 'index.js' with the 'locale.test.js' file. Otherwise, you will have to edit both files every time a new translation is added.

This is a much needed feature to prevent incomplete translation files to be added to the map.
Thank you.

**Comment by djbusstop** [comment]
Unfortunately, it's not simple, since jest is running in node it doesn't support es6 module imports. As I understand, that would require adding Babel, a new build tool. Do you think it's worth adding that build tool @unixjazz

**Comment by unixjazz** [comment]
@djbusstop IMHO, I think it would be good to not introduce more deps... the project already has +1500 dependencies. I defer to you, Tim and Jim to decide. We can totally live with 2 conf files to avoid adding another dependency.

**Comment by jimboweb** [comment]
Yes I agree.

**Pull request merged**
