### PR TITLE
Display layers in correct order

### PR DESCRIPTION
**Pull request by river-honer**
Resolves issue: https://github.com/antievictionmappingproject/covid-19-map/issues/18

Changes:
* Creates function for correcting the z order of layers, sorting what is vissible by the defined order
* Sets event listener to correct z order when layers are added

### CODE REVIEW

**Comment by river-honer** [comment]
I do think that having the order defined in an array is much easier to reason with than conditions around event names, and think if the plan is to go to polygon counties I would advocate for my solution.

But I agree with your point regarding preferring API methods. 

I can look again if there are API methods to avoid needing to check on the internals of the layer group object.

**Comment by river-honer** [comment]
Taking a look in to the docs, I think I can do what I'm doing with the LayerGroups methods instead of accessing the internals directly. Would you be open to this solution?

**Comment by river-honer** [comment]
@clhenrick Well, there is a method on map that does exactly what I was checking for. So I used it instead, the code is much nicer and all using the documented apis :)

**Comment by clhenrick** [comment]
@river-honer this looks much cleaner and I agree that defining the layer order in an array is easier to reason with than some if/else logic. Thank you kindly for your contribution!

**Pull request merged**
