### PR TITLE
Accreditation on sidebar

### PR DESCRIPTION
**Pull request by djbusstop**
Resolves: https://github.com/antievictionmappingproject/covid-19-map/issues/91

Links to the AEMP page for visitors to see the contributors.

@unixjazz would love some translations.

@erinmcel do you have other ideas for the text?

### CODE REVIEW

**Comment by erinmcel** [comment]
Hi! Other ideas in terms of what it should say? Other than what we've got written here, not sure.. https://antievictionmap.com/covid. What do you think?!

**Comment by djbusstop** [comment]
@erinmcel Did you envision to have the entire text from that page, or to link to that page?

**Comment by clhenrick** [comment]
Could be worth linking to the Github repo here as well

**Comment by djbusstop** [comment]
This is getting solved in the style update

**Pull request closed without merging**
