### PR TITLE
#49 Rent strike colors (anticipatorily rebased)

### PR DESCRIPTION
**Pull request by c-i-v-i-m**
- use single icon for confirmed and unsure rent-strike actions
- use svg icon
- color-match rent-strike action icons & cluster icon
- cleanup old rent-strike icons

### CODE REVIEW

**Comment by c-i-v-i-m** [comment]
For visual of chosen grey (#4d4d4d)
image

**Comment by timhitchins** [comment]
@c-i-v-i-m they already look so awesome!  I've been slammed with other work
today but will be able to take a closer look tomorrow and give better
feedback.  I am sorry the svg thing was such a pain in the ass.

**Comment by timhitchins** [comment]
@c-i-v-i-m It looks great!  I have no additional comments beyond what was already mentioned.

**Comment by c-i-v-i-m** [comment]
@clhenrick  @timhitchins  Thanks for the feedback.

I'll remove the colors from the title header, and we're good!

**Comment by c-i-v-i-m** [comment]
Updated:

- Rent strike marker description:
image

- Info window verbiage:
image

**Comment by clhenrick** [comment]
@c-i-v-i-m if you want to try the custom class svg marker, I just did a search and came across [my own gist on how to do this](https://gist.github.com/clhenrick/6791bb9040a174cd93573f85028e97af) from a while back (lol).

**Comment by clhenrick** [comment]
@c-i-v-i-m I added a WIP commit (6a2a4f8) demoing how to do it, but didn't clean up the rest of the code. Feel free to use or disregard. It involves in-lining the SVG code in the JS which isn't ideal.

**Comment by clhenrick** [comment]
@c-i-v-i-m I reverted that commit just FYI as I think your approach is cleaner. However, I did see that the icon will be the correct color if you add `fill="#4d4d4d"` to the opening `svg` tag in the `rent-strike.svg` file. Did this not work for you? Is the CSS filter a fallback to support legacy browsers?

**Comment by c-i-v-i-m** [comment]
You know... I quite feel like an idiot for not even realizing you could just change the fill color in the svg file. I guess my thinking was that having it all in css is ideal. One place to control the color of the cluster marker as well as the strike action markers.

I'll definitely update it for this PR. Since IE won't recognize the filter, it will respect the color in the file.

I've also been experimenting some more with the custom markers but haven't had any more success.. I think it might be possible by using object tags and passing in the iconUrl as the data property but I'm having issues with positioning and zooming. Something to do with the way leaflet is calculating the transform: translate3d. For example, when zoomed out Halifax is in the ocean
image or I zoom in and out and drag around the map, and I end up with a bunch of markers in the ocean: 
image. So I haven't quite given up but I'm running low on ideas. Might try to see if there's a conflict with the cluster plugin.

I'm also more than happy to just change the svg fill and merged this PR with the filter + fill as a fallback. We're basically covered, but we need to remember changing the svg color if/when we update the icon.

**Comment by clhenrick** [comment]
@c-i-v-i-m I noticed the same issue with the custom icon resulting in markers that were misaligned with their geographic coordinates. However, we don't need to use the custom icon for this, we can use the original method of just passing the path of the icon file to the regular `L.Icon` instance.

Also in our last meeting we discussed using an icon with a color other than grey to help it standout more against the new choropleth colors. Brett gave me a couple samples, I'll ask folks the Slack channel which they prefer and push the one we choose to this PR. Either way I don't think we'll need the CSS filter (or opacity) on the marker icon, but like you said we'll need to remember to update both the icon and cluster CSS when using a new color.

**Comment by c-i-v-i-m** [comment]
Now rebased on top of #54 and #55 : 
image

**Comment by clhenrick** [comment]
@c-i-v-i-m I sort of wish we had discussed rebasing v.s merging more before this PR was rebased. I'm concerned about the git history getting messed up after more changes are made in #55 and #54 prior to this PR being merged. We haven't used a rebase strategy in this repo yet and I think it's worth discussing our dev workflow a bit more before using `rebase`.

**Comment by clhenrick** [comment]
@c-i-v-i-m just making a note here (in addition to Slack) to please either revert the rebase or open a new PR with the latest changes for the marker and cluster colors. Thanks!

**Comment by clhenrick** [comment]
Superseded by #60

**Pull request closed without merging**
